### ISSUE TITLE
Errore in log quando si completa un ordine

### ISSUE THREAD

**Issue by dbarasti** [dbarasti/Sagration#1]
nel log viene catchato un errore con codice -2146824584:

`Error: Spawn C:\WINDOWS\SysWOW64\cscript.exe error
    at ChildProcess.child.on.exitCode (C:\Users\DavideBarasti\Codice\Sagration\node_modules\node-adodb\lib\spawn.js:120:37)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  process:
   { code: -2146824584,
     message: 'L\'operazione non è consentita se l\'oggetto è chiuso.' },
  exitCode: 0`

L'errore non è fatale e viene comunque eseguita l'operazione di completamento dell'ordine.

**Comment by dbarasti** [comment]
Si trattava di un errore nella query di update. Essa veniva eseguita con la funzione `connection.query(...)`
mentre doveva essere utilizzato il metoto `connection.exec(...)`
